[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[project]
name = "synloc"
version = "0.1.0"
description = "SoccerNet SynLoc 2026 Challenge - Single-Frame World-Coordinate Athlete Detection & Localization"
authors = [
  { name = "qbakom" },
]
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
]

[project.scripts]
synloc = "synloc.cli:cli"

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 99
src = ["src/synloc"]
include = ["pyproject.toml", "src/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.lint.isort]
known-first-party = ["synloc"]
force-sort-within-sections = true
